package agent

import (
	"fmt"
	"path"
	"strings"

	"github.com/KuroKodaNinja/iceclimber/internal/remote"
)

// renderRun builds an agent's per-agent launcher script (<root>/agent/<name>/run).
// It sources the agent's env (token, runtime env) when present, prepends NANA.md as
// persistent system context, then launches the agent with any operator args. On an
// interactive terminal it execs the agent clean (so its TUI keeps its tty); when
// stdout is not a tty (headless/-p runs) it mirrors the stream to session.log so the
// operator console can show it without a --agent-log flag. All paths are absolute.
func renderRun(d Descriptor, dir, binPath, nanaPath string) string {
	var b strings.Builder
	wired := "wired to NANA.md"
	if d.SystemPromptFlag == "" {
		wired = "this harness has no system-prompt flag, so NANA.md is not auto-wired"
	}
	fmt.Fprintf(&b, "#!/bin/sh\n")
	fmt.Fprintf(&b, "# iceclimber: launch the %s agent (%s). Generated by\n", d.DisplayName, wired)
	fmt.Fprintf(&b, "# `iceclimber agent install %s` — do not edit.\n", d.Name)
	fmt.Fprintf(&b, "set -eu\n")
	fmt.Fprintf(&b, "self=%s\n", remote.ShellQuote(dir))
	fmt.Fprintf(&b, "[ -f \"$self/env.sh\" ] && . \"$self/env.sh\"\n")
	fmt.Fprintf(&b, "bin=%s\n", remote.ShellQuote(binPath))

	// Decide capture before mangling the args: headless when stdout isn't a tty or a
	// print flag is present. An interactive run (tty, no print flag) is never tee'd —
	// its TUI needs the tty.
	fmt.Fprintf(&b, "headless=0\n")
	fmt.Fprintf(&b, "printrun=0\n")
	fmt.Fprintf(&b, "[ -t 1 ] || headless=1\n")
	if len(d.PrintFlags) > 0 {
		fmt.Fprintf(&b, "for a in \"$@\"; do case \"$a\" in %s) headless=1; printrun=1 ;; esac; done\n", strings.Join(d.PrintFlags, "|"))
	}

	// On a print run (a non-interactive task, -p present) with no explicit
	// --output-format, inject the parseable event stream so the bridged [NANA] pane
	// shows the agent's narration + tool calls — not just its final answer. Gated on
	// the print flag (not bare headlessness) so diagnostics like `--version` and a
	// caller's own --output-format are left exactly as given; -p makes stream-json valid.
	if len(d.StreamArgs) > 0 {
		fmt.Fprintf(&b, "if [ \"$printrun\" = 1 ]; then\n")
		fmt.Fprintf(&b, "  have_fmt=0\n")
		fmt.Fprintf(&b, "  for a in \"$@\"; do case \"$a\" in --output-format|--output-format=*) have_fmt=1 ;; esac; done\n")
		fmt.Fprintf(&b, "  [ \"$have_fmt\" = 0 ] && set -- %s \"$@\"\n", shellQuoteArgs(d.StreamArgs))
		fmt.Fprintf(&b, "fi\n")
	}

	if d.SystemPromptFlag != "" {
		// Prepend the system-prompt args (NANA.md contents) ahead of the operator's args.
		fmt.Fprintf(&b, "nana=%s\n", remote.ShellQuote(nanaPath))
		fmt.Fprintf(&b, "if [ -f \"$nana\" ]; then\n")
		fmt.Fprintf(&b, "  set -- %s \"$(cat \"$nana\")\" \"$@\"\n", remote.ShellQuote(d.SystemPromptFlag))
		fmt.Fprintf(&b, "else\n")
		fmt.Fprintf(&b, "  echo \"nana: NANA.md not found at $nana — launching without the Popo contract; run 'iceclimber bootstrap'\" >&2\n")
		fmt.Fprintf(&b, "fi\n")
	}

	fmt.Fprintf(&b, "if [ \"$headless\" = 1 ]; then\n")
	// Headless: mirror stdout+stderr to session.log so a serving process can bridge it.
	fmt.Fprintf(&b, "  log=\"$self/session.log\"\n")
	fmt.Fprintf(&b, "  printf '\\n=== nana session %%s ===\\n' \"$(date 2>/dev/null || echo)\" >>\"$log\" 2>/dev/null || true\n")
	fmt.Fprintf(&b, "  \"$bin\" \"$@\" 2>&1 | tee -a \"$log\"\n")
	fmt.Fprintf(&b, "else\n")
	fmt.Fprintf(&b, "  exec \"$bin\" \"$@\"\n") // interactive: keep the agent's tty
	fmt.Fprintf(&b, "fi\n")
	return b.String()
}

// shellQuoteArgs renders args as a space-joined, individually-quoted argument list
// for a `set --` line.
func shellQuoteArgs(args []string) string {
	q := make([]string, len(args))
	for i, a := range args {
		q[i] = remote.ShellQuote(a)
	}
	return strings.Join(q, " ")
}

// renderDispatcher builds the <root>/nana launcher. It discovers installed agents
// (each is a <root>/agent/<name>/run), selects one — an explicit first argument
// that names an installed agent, else the sole installed agent — and execs its
// launcher with the remaining args. It is generic (no agent baked in), so every
// `agent install` can rewrite it identically.
func renderDispatcher(root string) string {
	agents := path.Join(root, "agent")
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# iceclimber nana launcher — start an installed agent, wired to NANA.md.\n")
	b.WriteString("# Usage: nana [agent] [args-passed-to-the-agent...]\n")
	b.WriteString("# Generated by `iceclimber agent install` — do not edit.\n")
	b.WriteString("set -eu\n")
	fmt.Fprintf(&b, "agents=%s\n", remote.ShellQuote(agents))
	b.WriteString("list=''\n")
	b.WriteString("for r in \"$agents\"/*/run; do\n")
	b.WriteString("  [ -f \"$r\" ] || continue\n")
	b.WriteString("  list=\"$list $(basename \"$(dirname \"$r\")\")\"\n")
	b.WriteString("done\n")
	b.WriteString("sel=''\n")
	b.WriteString("if [ $# -gt 0 ] && [ -f \"$agents/$1/run\" ]; then sel=\"$1\"; shift; fi\n")
	b.WriteString("if [ -z \"$sel\" ]; then\n")
	b.WriteString("  n=0; first=''\n")
	b.WriteString("  for a in $list; do n=$((n+1)); first=\"$a\"; done\n")
	b.WriteString("  if [ \"$n\" -eq 1 ]; then sel=\"$first\";\n")
	b.WriteString("  elif [ \"$n\" -eq 0 ]; then echo \"nana: no agents installed — run 'iceclimber agent install <name>'\" >&2; exit 1;\n")
	b.WriteString("  else echo \"nana: multiple agents installed:$list — pick one: nana <agent> [args]\" >&2; exit 1; fi\n")
	b.WriteString("fi\n")
	b.WriteString("[ \"${1:-}\" = \"--\" ] && shift || true\n") // optional explicit separator
	b.WriteString("exec \"$agents/$sel/run\" \"$@\"\n")
	return b.String()
}
