package agent

import (
	"fmt"
	"path"
	"strings"

	"github.com/KuroKodaNinja/iceclimber/internal/remote"
)

// renderRun builds an agent's per-agent launcher script (<root>/agent/<name>/run).
// It sources the agent's env (token, runtime env) when present, then execs the
// agent binary with NANA.md injected as persistent system context and any operator
// args appended. All paths are absolute, so it runs from any working directory.
func renderRun(d Descriptor, dir, binPath, nanaPath string) string {
	var b strings.Builder
	wired := "wired to NANA.md"
	if d.SystemPromptFlag == "" {
		wired = "this harness has no system-prompt flag, so NANA.md is not auto-wired"
	}
	fmt.Fprintf(&b, "#!/bin/sh\n")
	fmt.Fprintf(&b, "# iceclimber: launch the %s agent (%s). Generated by\n", d.DisplayName, wired)
	fmt.Fprintf(&b, "# `iceclimber agent install %s` — do not edit.\n", d.Name)
	fmt.Fprintf(&b, "set -eu\n")
	fmt.Fprintf(&b, "self=%s\n", remote.ShellQuote(dir))
	fmt.Fprintf(&b, "[ -f \"$self/env.sh\" ] && . \"$self/env.sh\"\n")
	if d.SystemPromptFlag != "" {
		fmt.Fprintf(&b, "nana=%s\n", remote.ShellQuote(nanaPath))
		fmt.Fprintf(&b, "if [ -f \"$nana\" ]; then\n")
		fmt.Fprintf(&b, "  sp=\"$(cat \"$nana\")\"\n")
		fmt.Fprintf(&b, "  exec %s %s \"$sp\" \"$@\"\n", remote.ShellQuote(binPath), remote.ShellQuote(d.SystemPromptFlag))
		fmt.Fprintf(&b, "fi\n")
		fmt.Fprintf(&b, "echo \"nana: NANA.md not found at $nana — launching without the Popo contract; run 'iceclimber bootstrap'\" >&2\n")
	}
	fmt.Fprintf(&b, "exec %s \"$@\"\n", remote.ShellQuote(binPath))
	return b.String()
}

// renderDispatcher builds the <root>/nana launcher. It discovers installed agents
// (each is a <root>/agent/<name>/run), selects one — an explicit first argument
// that names an installed agent, else the sole installed agent — and execs its
// launcher with the remaining args. It is generic (no agent baked in), so every
// `agent install` can rewrite it identically.
func renderDispatcher(root string) string {
	agents := path.Join(root, "agent")
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# iceclimber nana launcher — start an installed agent, wired to NANA.md.\n")
	b.WriteString("# Usage: nana [agent] [args-passed-to-the-agent...]\n")
	b.WriteString("# Generated by `iceclimber agent install` — do not edit.\n")
	b.WriteString("set -eu\n")
	fmt.Fprintf(&b, "agents=%s\n", remote.ShellQuote(agents))
	b.WriteString("list=''\n")
	b.WriteString("for r in \"$agents\"/*/run; do\n")
	b.WriteString("  [ -f \"$r\" ] || continue\n")
	b.WriteString("  list=\"$list $(basename \"$(dirname \"$r\")\")\"\n")
	b.WriteString("done\n")
	b.WriteString("sel=''\n")
	b.WriteString("if [ $# -gt 0 ] && [ -f \"$agents/$1/run\" ]; then sel=\"$1\"; shift; fi\n")
	b.WriteString("if [ -z \"$sel\" ]; then\n")
	b.WriteString("  n=0; first=''\n")
	b.WriteString("  for a in $list; do n=$((n+1)); first=\"$a\"; done\n")
	b.WriteString("  if [ \"$n\" -eq 1 ]; then sel=\"$first\";\n")
	b.WriteString("  elif [ \"$n\" -eq 0 ]; then echo \"nana: no agents installed — run 'iceclimber agent install <name>'\" >&2; exit 1;\n")
	b.WriteString("  else echo \"nana: multiple agents installed:$list — pick one: nana <agent> [args]\" >&2; exit 1; fi\n")
	b.WriteString("fi\n")
	b.WriteString("[ \"${1:-}\" = \"--\" ] && shift || true\n") // optional explicit separator
	b.WriteString("exec \"$agents/$sel/run\" \"$@\"\n")
	return b.String()
}
