#!/usr/bin/env bash
# Generate an iceclimber.yaml pointing at the running Lima sandbox VM.
# Usage: test/lima/gen-config.sh [instance-name] [output-path] [remote-root]
# Invoked by `make sandbox-config` (2 args) and `make demo-config` (3 args).
set -euo pipefail

SBX="${1:-iceclimber-sandbox}"
OUT="${2:-iceclimber.yaml}"
ROOT="${3:-}"   # optional: pin remote_root so the tree path is predictable
CFG="$HOME/.lima/$SBX/ssh.config"

if [ ! -f "$CFG" ]; then
	echo "no ssh.config for '$SBX' — is it up? run 'make sandbox-up' first" >&2
	exit 1
fi

PORT=$(awk '/^[[:space:]]*Port /{print $2; exit}' "$CFG")
USER_=$(awk '/^[[:space:]]*User /{print $2; exit}' "$CFG")
IDENT=$(awk '/^[[:space:]]*IdentityFile /{gsub(/"/,"",$2); print $2; exit}' "$CFG")

# The VM regenerates host keys per instance, so scan fresh into a temp file.
KH=$(mktemp "${TMPDIR:-/tmp}/iceclimber-known_hosts.XXXXXX")
ssh-keyscan -T 10 -p "$PORT" 127.0.0.1 > "$KH" 2>/dev/null

cat > "$OUT" <<EOF
# Generated by 'make sandbox-config' for the Lima sandbox '$SBX'. Gitignored.
sandbox_id: $SBX
ssh:
  host: 127.0.0.1
  port: $PORT
  user: $USER_
  identity_file: $IDENT
  known_hosts: $KH
EOF
if [ -n "$ROOT" ]; then
	echo "remote_root: $ROOT" >> "$OUT"
fi

echo "wrote $OUT  (sandbox $SBX, $USER_@127.0.0.1:$PORT${ROOT:+, root $ROOT})"
echo "next:  ./iceclimber bootstrap   then   ./iceclimber serve"
